### ISSUE TITLE
jasna's commits should be ascribed correctly

### ISSUE THREAD

**Issue by merlinorg** [learningobjectsinc/scaloi#3]

**Comment by merlinorg** [comment]
and @hrhino can you |> me your email addr pls?

**Comment by hrhino** [comment]
@JasnaMRB has been requested to do her share of this. If she were to indicate to me her preferred email address I would be able to mailmap it in for posterity.

**Comment by hrhino** [comment]
> and @hrhino can you |> me your email addr pls?

done.

**Comment by hrhino** [comment]
@mtieu this changes no behaviour, no tests needed.
